#!/usr/bin/env python

# Echo client program
import socket
import sys

try:
    HOST = 'localhost'    # The remote host
    PORT = 4222           # The same port as used by the server
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((HOST, PORT))
    s.send(' '.join(sys.argv[1:])+"\n")
    s.close()
except:
    # die silently
    pass

